Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: com.revature.get_cards.GetCardsHandler
      CodeUri: C:\Users\kimtr\IdeaProjects\getCards
      Runtime: java8.al2