package com.revature.get_cards;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import lombok.Data;

/**
 * The Card class is a POJO representing the Card model.
 */

@Data
@DynamoDBDocument
public class Card {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String setId;

    @DynamoDBAttribute
    private String question;

    @DynamoDBAttribute
    private String answer;


}
